name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install -y libbsd-dev
        sudo apt-get install -y build-essential
    - name: make
      run: make all DISTRO=ubuntu
    - name: make test
      run: make test DISTRO=ubuntu
