name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker container
        run: |
          docker pull ubuntu:latest
          docker run -d --name build-container -v ${{ github.workspace }}:/workspace ubuntu:latest tail -f /dev/null

      - name: Install dependencies inside Docker
        run: |
          docker exec build-container bash -c "
          apt-get update &&
          apt-get install -y libbsd-dev build-essential
          "

      - name: Build project inside Docker
        run: |
          docker exec build-container bash -c "
          cd /workspace &&
          make all DISTRO=ubuntu
          "

      - name: Test project inside Docker
        run: |
          docker exec build-container bash -c "
          cd /workspace &&
          make tests DISTRO=ubuntu
          "

      - name: Clean up Docker container
        run: docker stop build-container && docker rm build-container
